### ISSUE TITLE
seed-peer keepalive manager fails

### ISSUE THREAD

**Issue by Gyeah11** [dragonflyoss/Dragonfly2#2023]
### Bug report:

I've installed dragonfly 2.0.8 using docker-compose and seem to work well for 2 nodes that are near each other 
( same datacenter ), but not so good when i add another one into a DC far away, ~200 ms

i've installed `one node` with `all the containers`. `( Europe )`

i've installed `one node` only with  `dfdaemon/seed-peer` . `( Europe )`

i'm installing `another node` with  with `dfdaemon/seed-peer` in `USA` and this seems to fail at the communication with the manager

configuration files  for `dfdaemon/seed-peer` nodes in `USA/Europe` are the same (i've diff them )

i've done some basic connectivity tests and node from ```USA``` and it can reach manager to make the `keepalived`

```
[root@dragonfly-seed-peer-usa ~]  # curl http://manager_ip:65003/ -v
* Rebuilt URL to: http://manager_ip:65003/
*   Trying MANAGER_IP...
* TCP_NODELAY set
* Connected to MANAGER_IP (MANAGER_IP) port 65003 (#0)
```

and this are the network ports allowed between all `dragonfly2` nodes
i've modified proxy port from `65001` to `80`
```
65006
65008
65007
65003
8080
8002
65002
65000
40901
40902
80
```
on the node where is the `dragonfly-manager` , i have this logs , when the new `seed-peer from USA` tries to join the cluster
```bash
==> /var/log/dragonfly/dragonfly-manager/core.log <==
{"level":"debug","ts":"2023-01-25 09:10:27.428","caller":"rpcserver/rpcserver.go:515","msg":"list schedulers, version v2.0.8, commit 8a7d951","hostname":"dragonfly-seed-peer.REDACTED","ip":"10.60.REDACTED"}
{"level":"debug","ts":"2023-01-25 09:10:27.428","caller":"rpcserver/rpcserver.go:540","msg":"manager:peers:dragonfly-seed-peer.REDACTED:schedulers cache miss","hostname":"dragonfly-seed-peer.REDACTED","ip":"10.60.REDACTED"}
{"level":"debug","ts":"2023-01-25 09:10:27.430","caller":"rpcserver/rpcserver.go:547","msg":"list scheduler clusters [scheduler-cluster-1] with hostInfo map[string]string{\"idc\":\"\", \"location\":\"\", \"net_topology\":\"\", \"security_domain\":\"\"}","hostname":"dragonfly-seed-peer.REDACTED","ip":"10.60.REDACTED"}
{"level":"debug","ts":"2023-01-25 09:10:27.430","caller":"rpcserver/rpcserver.go:553","msg":"find matching scheduler cluster [scheduler-cluster-1]","hostname":"dragonfly-seed-peer.REDACTED","ip":"10.60.REDACTED"}

==> /var/log/dragonfly/dragonfly-manager/grpc.log <==
{"level":"info","ts":"2023-01-25 09:10:27.431","caller":"zap/server_interceptors.go:39","msg":"finished unary call with code OK","grpc.start_time":"2023-01-25T09:10:27Z","grpc.request.deadline":"2023-01-25T09:12:27Z","system":"grpc","span.kind":"server","grpc.service":"manager.Manager","grpc.method":"ListSchedulers","grpc.code":"OK","grpc.time_ms":3.538}

==> /var/log/dragonfly/dragonfly-manager/core.log <==
{"level":"debug","ts":"2023-01-25 09:10:27.452","caller":"rpcserver/rpcserver.go:515","msg":"list schedulers, version v2.0.8, commit 8a7d951","hostname":"dragonfly-seed-peer.REDACTED","ip":"10.60.REDACTED"}
{"level":"debug","ts":"2023-01-25 09:10:27.452","caller":"rpcserver/rpcserver.go:535","msg":"manager:peers:dragonfly-seed-peer.REDACTED:schedulers cache hit","hostname":"dragonfly-seed-peer.REDACTED","ip":"10.60.REDACTED"}

==> /var/log/dragonfly/dragonfly-manager/grpc.log <==
{"level":"info","ts":"2023-01-25 09:10:27.452","caller":"zap/server_interceptors.go:39","msg":"finished unary call with code OK","grpc.start_time":"2023-01-25T09:10:27Z","grpc.request.deadline":"2023-01-25T09:12:27Z","system":"grpc","span.kind":"server","grpc.service":"manager.Manager","grpc.method":"ListSchedulers","grpc.code":"OK","grpc.time_ms":0.26}
{"level":"info","ts":"2023-01-25 09:10:27.750","caller":"zap/server_interceptors.go:39","msg":"finished unary call with code OK","grpc.start_time":"2023-01-25T09:10:27Z","grpc.request.deadline":"2023-01-25T09:12:27Z","system":"grpc","span.kind":"server","grpc.service":"manager.Manager","grpc.method":"UpdateSeedPeer","grpc.code":"OK","grpc.time_ms":3.248}

==> /var/log/dragonfly/dragonfly-manager/core.log <==
{"level":"error","ts":"2023-01-25 09:10:27.778","caller":"rpcserver/rpcserver.go:985","msg":"keepalive failed for the first time: rpc error: code = Canceled desc = context canceled","stacktrace":"d7y.io/dragonfly/v2/manager/rpcserver.(*Server).KeepAlive\n\t/go/src/d7y.io/dragonfly/v2/manager/rpcserver/rpcserver.go:985\nd7y.io/api/pkg/apis/manager/v1._Manager_KeepAlive_Handler\n\t/go/pkg/mod/d7y.io/api@v1.2.9/pkg/apis/manager/v1/manager.pb.go:4441\ngithub.com/grpc-ecosystem/go-grpc-middleware/recovery.StreamServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/recovery/interceptors.go:51\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-middleware/validator.StreamServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/validator/validator.go:72\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-middleware/logging/zap.StreamServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/logging/zap/server_interceptors.go:53\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:121\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngo.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.StreamServerInterceptor.func1\n\t/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.36.3/interceptor.go:432\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-middleware/ratelimit.StreamServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/ratelimit/ratelimit.go:34\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:58\ngoogle.golang.org/grpc.(*Server).processStreamingRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1636\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1717\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:965"}

==> /var/log/dragonfly/dragonfly-manager/grpc.log <==
{"level":"error","ts":"2023-01-25 09:10:27.778","caller":"zap/server_interceptors.go:61","msg":"finished streaming call with code Unknown","grpc.start_time":"2023-01-25T09:10:27Z","system":"grpc","span.kind":"server","grpc.service":"manager.Manager","grpc.method":"KeepAlive","error":"rpc error: code = Unknown desc = rpc error: code = Canceled desc = context canceled","grpc.code":"Unknown","grpc.time_ms":49.003,"stacktrace":"github.com/grpc-ecosystem/go-grpc-middleware/logging/zap.StreamServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/logging/zap/server_interceptors.go:61\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:121\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngo.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.StreamServerInterceptor.func1\n\t/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.36.3/interceptor.go:432\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-middleware/ratelimit.StreamServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/ratelimit/ratelimit.go:34\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:58\ngoogle.golang.org/grpc.(*Server).processStreamingRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1636\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1717\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:965"}

==> /var/log/dragonfly/dragonfly-manager/core.log <==
{"level":"error","ts":"2023-01-25 09:10:27.945","caller":"rpcserver/rpcserver.go:985","msg":"keepalive failed for the first time: rpc error: code = Canceled desc = context canceled","stacktrace":"d7y.io/dragonfly/v2/manager/rpcserver.(*Server).KeepAlive\n\t/go/src/d7y.io/dragonfly/v2/manager/rpcserver/rpcserver.go:985\nd7y.io/api/pkg/apis/manager/v1._Manager_KeepAlive_Handler\n\t/go/pkg/mod/d7y.io/api@v1.2.9/pkg/apis/manager/v1/manager.pb.go:4441\ngithub.com/grpc-ecosystem/go-grpc-middleware/recovery.StreamServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/recovery/interceptors.go:51\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-middleware/validator.StreamServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/validator/validator.go:72\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-middleware/logging/zap.StreamServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/logging/zap/server_interceptors.go:53\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:121\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngo.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.StreamServerInterceptor.func1\n\t/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.36.3/interceptor.go:432\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-middleware/ratelimit.StreamServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/ratelimit/ratelimit.go:34\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:58\ngoogle.golang.org/grpc.(*Server).processStreamingRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1636\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1717\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:965"}

==> /var/log/dragonfly/dragonfly-manager/grpc.log <==
{"level":"error","ts":"2023-01-25 09:10:27.945","caller":"zap/server_interceptors.go:61","msg":"finished streaming call with code Unknown","grpc.start_time":"2023-01-25T09:10:27Z","system":"grpc","span.kind":"server","grpc.service":"manager.Manager","grpc.method":"KeepAlive","error":"rpc error: code = Unknown desc = rpc error: code = Canceled desc = context canceled","grpc.code":"Unknown","grpc.time_ms":47.681,"stacktrace":"github.com/grpc-ecosystem/go-grpc-middleware/logging/zap.StreamServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/logging/zap/server_interceptors.go:61\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:121\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngo.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.StreamServerInterceptor.func1\n\t/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.36.3/interceptor.go:432\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-middleware/ratelimit.StreamServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/ratelimit/ratelimit.go:34\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:58\ngoogle.golang.org/grpc.(*Server).processStreamingRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1636\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1717\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:965"}
```

and on the seed-peer in USA i see this
```
goroutine 148 [running]:
stathat.com/c/consistent.(*Consistent).Members(0x1c25c90?)
  /go/pkg/mod/stathat.com/c/consistent@v1.0.0/consistent.go:134 +0x57
d7y.io/dragonfly/v2/pkg/balancer.(*ConsistentHashingPickerBuilder).GetCircle(0xc000e1c030)
  /go/src/d7y.io/dragonfly/v2/pkg/balancer/consistent_hashing.go:88 +0x39
d7y.io/dragonfly/v2/pkg/rpc/scheduler/client.(*client).AnnounceHost(0xc0004cac80, {0x1c25c58, 0xc000112000}, 0xc0001f85a0, {0x0, 0x0, 0x0})
  /go/src/d7y.io/dragonfly/v2/pkg/rpc/scheduler/client/client.go:228 +0x118
d7y.io/dragonfly/v2/client/daemon/announcer.(*announcer).announceToScheduler(0xc00028c320)
  /go/src/d7y.io/dragonfly/v2/client/daemon/announcer/announcer.go:122 +0x6f
d7y.io/dragonfly/v2/client/daemon/announcer.(*announcer).Serve(0xc00028c320)
  /go/src/d7y.io/dragonfly/v2/client/daemon/announcer/announcer.go:102 +0xe5
d7y.io/dragonfly/v2/client/daemon.(*clientDaemon).Serve.func8()
  /go/src/d7y.io/dragonfly/v2/client/daemon/daemon.go:662 +0x86
created by d7y.io/dragonfly/v2/client/daemon.(*clientDaemon).Serve
  /go/src/d7y.io/dragonfly/v2/client/daemon/daemon.go:660 +0xcbc
stderr redirect at 2023-01-25 06:32:22.100405509 +0000 UTC m=+0.036853497
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0xce3237]
```
### Environment:
- Dragonfly version: 2.0.8
- OS: rocky8
- Kernel (e.g. `uname -a`): 
```
Linux dragonfly-seed-peer.redacted 6.1.7-1.el8.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jan 17 12:49:00 EST 2023 x86_64 x86_64 x86_64 GNU/Linux
```
- Others:
docker compose deployment

**Comment by Gyeah11** [comment]
after i've upgraded to `v2.0.9-beta.0` problem got solved
